apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-lens-web

resources:
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: kube-lens-web
  app.kubernetes.io/component: dashboard
  app.kubernetes.io/managed-by: kustomize
